sudo: required
services:
  - docker
before_install:
  - docker build -t sunnyjohal/docker-react -f Dockerfile.dev .
script:
  - docker container run sunnyjohal/docker-react npm run test -- --coverage
